#    docker-compose -f docker-compose.yml up -d
version: '3.1'
services:
#    cassandra:
#       image: cassandra
#       ports:
#          - '9042:9042'

        
   mysql:
      image: mysql
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: root
      ports:
         - '3306:3306'
         
   elasticsearch:
      #image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
      image: elasticsearch:7.4.0
      ports:
         - 9200:9200
         - 9300:9300
      environment:
         discovery.type: single-node


   ms-rabbitmq:
      image: rabbitmq:3-management
      ports:
         - '5672:5672'
         - '15672:15672'
      environment:
         - RABBITMQ_DEFAULT_USER=celal
         - RABBITMQ_DEFAULT_PASS=celal