server:
   port: 8501
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8500/eureka/
spring:
   application:
      name: Account-Service
   datasource:
      url: jdbc:postgresql://localhost:5432/Okul
      username: postgres
      password: celal371
      driver-class-name: org.postgresql.Driver
   jpa:
      hibernate:
      ddl-auto: update
      generate-ddl: true
      properties:
         hibernate:
            temp:
               use_jdbc_metadata_defaults: false

      database-platform: org.hibernate.dialect.PostgreSQL9Dialect