server:
   port: 8502
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8500/eureka/
         
spring:
   application:
      name: ticket-service
   datasource:
      url: jdbc:mysql://localhost:3306/microserviceapp
      username: root
      password: root
   jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
         ddl-auto: update
   rabbitmq:
      username: celal
      password: celal
   cloud:
      stream:
         bindings:
            output:
               destination: msqueue
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  